appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Cq+jst/h98bcagLhSoxX7L9LskCt+RSOudhKc0/O9mfleYDZ4L7QX82/TxdSmzvlHhGNgyyadzyVQcyqWgZ6oGT5kVTaDdWeAT9gRmB3ts/+brn2OrfvT+GZ8a8TbZWMBn+KY8q57+NOXX2hnwBfm1ukSq+mWZ3XBFbwUYU4rVgRZzSeMzwGhy0dKjv+VMybKJgODgpGkkxqSO3nCJzvJdWHHeMaB3GNB31iNx3cJS50IJk26WeWmiI8AbO7al0n3WPCgJyghvFwHg7g7HfOvoHKy/PviB3rtYk37uEVikWpsNJCU7/103QMmA6QYJNJHIT1e6s97gXzeNnIDCT8fPwS9Mfr9Fcqjx/ccu/2H5NFStOdukgJai8SFFTRQlxdtFWfjI2PzIdL4+KJiuFoi0U7pfQJ8C5n767f+aBruIQlhXeFtQ5hYFaE0/g43Xb5GZMH9kjDiheZQjVHu7Q/ssi/KfiN0NM8+D1P7QoVbpjiGCaAgyOXFZXYz1YDmp54N3QXlqUnJTjZ365ysY+75nM0U/3r26l9ksApoYoCqtTZoMGsPYU9D7DEzLXZF0KThRU9CqdMaqNzGuW9xCSmuDu79H5amcewYqTbVzwzu2fYSfoSPkty53Idek3Rq09hMRQJTBeuDx19cFvTVYBbQt+6RFRHXMfeChaV++FBPHg=}
bot:
  automerge: true
